require("kittawat.plugins_configs.lspconfig_setup")
require("kittawat.plugins_configs.undotree")
require("kittawat.plugins_configs.telescope")
require("kittawat.plugins_configs.treesitter")
require("kittawat.plugins_configs.vim_fugitive")
